# Generated by Django 2.2.15 on 2022-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220106_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateTimeField(auto_now=True, verbose_name='DOB'),
        ),
    ]
