# Generated by Django 2.2.15 on 2022-01-07 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220106_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Designation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Birth'),
        ),
    ]
