# Generated by Django 2.2.15 on 2022-01-07 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220107_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dob',
        ),
        migrations.AddField(
            model_name='account',
            name='dt_ob',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
